import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

const cases = [
  {title:'Et nyt fællesskab',text:'Alex er lige begyndt på universitetet og er flyttet til en ny by. På holdet er der allerede opstået små grupper, og mange kender hinanden fra introduktionsugen. Alex har et studiejob om aftenen og har derfor ikke været med til alle de sociale arrangementer.', end:'En eftermiddag inviterer en medstuderende Alex til en fælles middag. Alex vil gerne lære de andre bedre at kende, men har samtidig en vagt på arbejdet. Invitationen giver anledning til at overveje, hvad det kræver at blive en del af fællesskabet.'},
  {title:'Plads i samtalen',text:'Sam deltager i en studiegruppe med fire andre studerende. Gruppen mødes hver uge for at diskutere pensum. To af medlemmerne taler ofte først og sætter retningen for samtalen, mens Sam typisk lytter og tager noter.',end:'Ved næste møde foreslår et gruppemedlem, at alle på skift indleder diskussionen. Sam får ansvaret for den første introduktion og overvejer, hvordan det vil ændre deltagelsen i gruppen.'},
  {title:'Hverdagen mellem to steder',text:'Robin bor hos sin familie og pendler til universitetet. Flere medstuderende bor tæt på campus og mødes ofte efter undervisningen. Robin tager som regel hjem med det samme for at hjælpe med opgaver i hjemmet.',end:'En dag bliver et gruppearbejde lagt sent på eftermiddagen. Robin må finde en løsning, der både giver plads til studiet og familiens forventninger. Gruppen diskuterer, hvordan de kan organisere deres samarbejde.'},
  {title:'Et fælles ansvar',text:'Charlie bor på et kollegium, hvor beboerne deler køkken. Nogle bruger meget tid på fælles aktiviteter, mens andre foretrækker at holde sig for sig selv. På det seneste har der været uenighed om oprydningen.',end:'På et beboermøde foreslår en af de andre en fælles ordning med faste opgaver. Charlie overvejer, hvordan reglerne kan tage hensyn til forskellige hverdage og samtidig skabe et ansvar for fællesskabet.'}
];
const labels=['Velkommen','Om dig','Din case','Tak'];
function App(){
 const [step,setStep]=useState(0);
 const [answers,setAnswers]=useState({age:'',gender:'',recruitment:''});
 const [consent,setConsent]=useState(false);
 const [caseIndex,setCaseIndex]=useState(null);
 const [downloaded,setDownloaded]=useState(false);
 const change=(key,value)=>setAnswers(a=>({...a,[key]:value}));
 function assign(e){e.preventDefault(); if(caseIndex===null){const count=Number(localStorage.getItem('perspektiv-demo-count')||0);setCaseIndex(count%4);localStorage.setItem('perspektiv-demo-count',String(count+1));}setStep(2);window.scrollTo(0,0);}
 function download(){const blob=new Blob([JSON.stringify({prototype:true,answers,case:caseIndex+1},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='demo-besvarelse.json';a.click();URL.revokeObjectURL(url);setDownloaded(true);}
 return <div className="app"><header><a className="brand" href="#" onClick={e=>{e.preventDefault();}}><span className="brand-icon">p</span>perspektiv<span className="brand-dot">.</span></a><span className="header-note">SOCIOLOGISK UNDERSØGELSE</span><span className="privacy"><span/> Anonym deltagelse</span></header>
 <main><nav className="progress" aria-label="Fremdrift">{labels.map((label,i)=><div key={label} className={`progress-item ${i===step?'active':''} ${i<step?'done':''}`} aria-current={i===step?'step':undefined}><span>{i<step?'✓':i+1}</span><small>{label}</small></div>)}</nav>
 <section className={`card step-${step}`}>
 {step===0&&<><div className="intro-art" aria-hidden="true"><div className="orb orb-one"/><div className="orb orb-two"/><div className="art-lines">✳</div><span className="art-label">Forskellige liv. Nye perspektiver.</span></div><div className="content"><p className="eyebrow">DIT PERSPEKTIV TÆLLER</p><h1>Små fortællinger.<br/><em>Store perspektiver.</em></h1><p className="lead">Hvordan oplever vi fællesskaber og hverdagsliv? Bidrag til en sociologisk undersøgelse med dit perspektiv.</p><div className="info-row"><span>◷ &nbsp; Ca. 3 minutter</span><span>◎ &nbsp; Én kort case</span></div><div className="soft-note"><strong>En lille undersøgelse om det, vi deler</strong><p>Først svarer du på et par generelle spørgsmål. Derefter læser du en kort fortælling og afslutter din deltagelse. Der er ingen spørgsmål efter fortællingen.</p></div><label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>Jeg har læst introduktionen og ønsker at deltage frivilligt.</span></label><button disabled={!consent} onClick={()=>setStep(1)}>Start undersøgelsen <span>→</span></button><p className="fine-print">Du kan stoppe når som helst ved at lukke siden.</p></div></>}
 {step===1&&<div className="content"><p className="eyebrow">TRIN 1 · LIDT OM DIG</p><h1>Vi starter med<br/><em>det generelle.</em></h1><p className="lead">Et par baggrundsspørgsmål, før du møder din case. Dine svar påvirker ikke, hvilken case du får.</p><form onSubmit={assign}><label className="field">Hvor gammel er du?<select required value={answers.age} onChange={e=>change('age',e.target.value)}><option value="">Vælg aldersgruppe</option>{['Under 18','18–24','25–29','30–39','40 eller derover','Ønsker ikke at oplyse'].map(x=><option key={x}>{x}</option>)}</select></label><fieldset><legend>Hvilket køn identificerer du dig som?</legend><div className="options">{['Kvinde','Mand','Nonbinær','Andet','Ønsker ikke at oplyse'].map(x=><label className={`option ${answers.gender===x?'selected':''}`} key={x}><input required type="radio" name="gender" value={x} checked={answers.gender===x} onChange={()=>change('gender',x)}/>{x}</label>)}</div></fieldset><label className="field">Hvordan fandt du undersøgelsen?<select required value={answers.recruitment} onChange={e=>change('recruitment',e.target.value)}><option value="">Vælg en mulighed</option>{['Via undervisningen','Via en medstuderende','Sociale medier','Andet','Ønsker ikke at oplyse'].map(x=><option key={x}>{x}</option>)}</select></label><div className="actions"><button type="button" className="back" onClick={()=>setStep(0)}>← Tilbage</button><button type="submit">Videre til din case <span>→</span></button></div></form></div>}
 {step===2&&<div className="content"><p className="eyebrow">TRIN 2 · EN FORTÆLLING FRA HVERDAGEN</p><h1>{cases[caseIndex].title}<span className="title-period">.</span></h1><p className="lead">Læs fortællingen i dit eget tempo. Der er ingen rigtige eller forkerte perspektiver.</p><article className="case-text"><span className="quote" aria-hidden="true">“</span><p>{cases[caseIndex].text}</p><p>{cases[caseIndex].end}</p></article><p className="reading-note">Når du har læst fortællingen, kan du afslutte undersøgelsen.</p><div className="actions"><button className="back" onClick={()=>setStep(1)}>← Tilbage</button><button onClick={()=>{setStep(3);window.scrollTo(0,0);}}>Afslut og send <span>→</span></button></div><p className="fine-print">Prototype: Knappen afslutter demoen. Ingen svar sendes.</p></div>}
 {step===3&&<div className="content thank-you"><div className="thank-icon">✓</div><p className="eyebrow">TAK FOR DIN TID</p><h1>Et perspektiv<br/><em>mere.</em></h1><p className="lead">Du har gennemført demoen. Tak, fordi du prøvede undersøgelsen.</p><div className="soft-note"><strong>Dette er en prototype</strong><p>Dine svar er ikke sendt eller gemt på en server. Du kan hente en lokal kopi for at se, hvordan en besvarelse bliver struktureret.</p></div><button onClick={download}>{downloaded?'Hent demo-svar igen':'Hent demo-svar'} <span>↓</span></button><button className="restart" onClick={()=>{setStep(0);setAnswers({age:'',gender:'',recruitment:''});setConsent(false);setCaseIndex(null);setDownloaded(false);}}>Prøv en ny besvarelse ↗</button></div>}
 </section><footer><span>perspektiv · Sociologi</span><span>Frivillig deltagelse · Ingen navn eller e-mail</span></footer><div className="demo-label">PROTOTYPE <span>Eksempelindhold · Casefordeling tælles kun i denne browser</span></div></main></div>
}
createRoot(document.getElementById('root')).render(<App/>);
